### ISSUE TITLE
Gama Server GUI: Gama Server Error for a valid GAML model

### ISSUE THREAD

**Issue by leonsi7** [gama-platform/gama.old#3923]
**Describe the bug**
I'm working with Gama Server. I wrote a simple models which works perfectly with Gama Server 1.9.2 (loading, and running) and which creates a Gama Server Error with Gama 1.9.3. Actually, this models creates an exception in Gama Server but after that the simulation is unsuable because I cannot get the experiment ID

**To Reproduce**
1. Launch to Gama Headless Server
2. Load the following model using Websocket:
```java
model Testgamaserver

/*This model allow the creation of VrHedset species which is
for the example a dot which run in a square and send its position to the monitor*/

global {

	reflex  send_simulation_info when:every(1 #cycle){
		map<string, unknown> json;
		map<string, unknown> sending_message;
		loop vr_headset over:VrHeadset {
			map<string,unknown> info_json;
			map<string, unknown> location_json;
			location_json["x"] <- vr_headset.location.x;
			location_json["y"] <- vr_headset.location.y;
			info_json["position"] <- location_json;
			json[vr_headset.id] <- info_json;

		}
		write as_json_string(json);
	}
	
	action killVrHeadset(string id_vr) {
		loop vr_headset over: VrHeadset {
			if (vr_headset.id = id_vr){
				ask vr_headset {
					do die;
				}
			}
		}
	}
}

species VrHeadset skills:[moving] {
	
	string id;
	
	rgb color <- rgb(rnd(0,255),rnd(0,255),rnd(0,255));

    reflex move {
        do wander;
    }
	
    aspect base {
    	draw circle(1) color:color;
    }
    
}

// Créez un environnement avec une zone spécifique où RandomGuy se déplace
experiment test type:gui {
    float minimum_cycle_duration <- 0.001 #second;
    output {
    	display map {
			species VrHeadset aspect: base;
		}
    }
}
```
5. See the websocket message:
```JSON
{ type: 'GamaServerError', content: 'Exception in Application'}
```
Due to this message, I don't receive the experiment id and I cannot interact with the simulation.

When I look on the console of Gama Server, I see: 
```console
Exception in Application
java.lang.NullPointerException: Cannot invoke "java.util.Collection.spliterator()" because "collection" is null
	at one.util.streamex.StreamEx.of(StreamEx.java:2256)
	at msi.gama.lang.gaml.validation.GamlModelBuilder.compile(GamlModelBuilder.java:126)
	at msi.gama.runtime.server.DefaultServerCommands.LOAD(DefaultServerCommands.java:65)
	at msi.gama.runtime.server.CommandExecutor.lambda$1(CommandExecutor.java:120)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Expected behavior**
The simulation must normally be lauched correcly like with Gama server 1.9.2

**Desktop (please complete the following information):**
 - OS: macOS
 - GAMA version: 1.9.3

**Comment by lesquoyb** [comment]
I cannot reproduce it on windows11, are you running gama from a release (dmg file) or from eclipse ?
If it's from a release try to do it again from eclipse with the latest commits

**Comment by AlexisDrogoul** [comment]
Although not strictly a fix for this, I have committed some code that will eliminate the NPE and then provide the correct list of compilation errors occurring. Please test and report !

**Comment by leonsi7** [comment]
Hi, I have a new error with GAMA Server GUI:

Describe the bug
I'm working with Gama Server GUI. I wrote a simple models which works perfectly with Gama Server 1.9.2 (loading, and running) and which creates a Gama Server Error with Gama 1.9.3. Actually, this models creates an exception in Gama Server and does not send a weboscket message about the error/exception

To Reproduce
Please use my newly developed NodeJS server [here](https://github.com/leonsi7/gama-server-middleware). Follow the installation intructions and load /models/model1.gaml. You can try it with gama server 1.9.2 and gama server GUI to compare the results.
The exception returned by Gama Server GUI in the console is: 
```java
java.lang.NullPointerException: Cannot invoke "Object.toString()" because the return value of "msi.gama.util.IMap.get(Object)" is null
	at msi.gama.runtime.server.CommandExecutor.process(CommandExecutor.java:112)
	at msi.gama.runtime.server.CommandExecutor.lambda$0(CommandExecutor.java:66)
	at java.base/java.lang.Thread.run(Thread.java:833)
```
Expected behavior
The simulation must normally be lauched correcly like with Gama server 1.9.2

Desktop (please complete the following information):

    OS: macOS
    GAMA version: Gama Server GUI 1.9.3

**Comment by AlexisDrogoul** [comment]
This one has been tested and seems to work well !
