### ISSUE TITLE
Among operator does not work with a list of strings

### ISSUE THREAD

**Issue by lesquoyb** [gama-platform/gama.old#3429]
**Describe the bug**
The `among` operator doesn't work on every kind of lists. If you try to use it with a list of string you get a compilation error, but it works as expected with a list of int.

**To Reproduce**
Try to run:
```
string state <- "wait for players" among ["wait for players", "do stuff"];
```

![image](https://user-images.githubusercontent.com/6374469/169986241-a33f8b20-9fa1-460e-8927-81c397f55fad.png)

I'm almost certain it used to work in 1.8(.1?)

**Comment by lesquoyb** [comment]
Oops, looks like I just misunderstood the use of this operator. Closing
