### ISSUE TITLE
Graph is null

### ISSUE THREAD

**Issue by pcaillou** [gama-platform/gama.old#656]
```
Hello,

I have just installed the SVN version and I do not understand why I can not use my
graph.
I tried the following and very basic model: 

model MyModel

global {
    graph my_graph  <- load_graph_from_file(
                "dgs",
                "../BarabasiGenerated.dgs", 
                nodeSpecy,
                edgeSpecy   
        );

    init {
        write my_graph ;        
    }
}

entities {
    species nodeSpecy {
        rgb color <- rgb('black') ;   
        aspect base { 
            draw circle(3) color: color ;
        } 
    }

    species edgeSpecy  { 
        rgb color <- rgb('blue') ; 
        aspect base {
            draw shape color: color ;   
        }
    }
}

environment;

experiment exp_graph type: gui {
    output {
        display display_network refresh_every: 1 {
            species edgeSpecy aspect: base ; 
            species nodeSpecy aspect: base ;
        }
    }
}

It is written "null" in the console but the display show the correct graph.
Actually, it is like my graph was not instantiated at all... If I try with an add_edge
operator, I get a Java Null pointer exception. I allso tried with another graph file
with the same result.

Furthermore, the following piece of code make a compilation error (unknown statement
graphdisplay) :
graphdisplay monNom2 graph: my_graph lowquality:true ;

All of this code works perfectly on the 1.6PR version.

I am a new user of this platform, so, have I made a mistake? Or is there a bug somewhere?



```

Original issue reported on code.google.com by `thibaut.demare` on 2013-09-27 10:21:13
